version: '3'
networks:
  radio.net:
    driver: bridge

services:
  radio.api:
    image: 'canals/php:latest'
    env_file: radio.env
    ports:
      - '2080:80'
    volumes:
      - ../server/public:/var/www/html
      - ../server:/var/www
    working_dir: /var/www
    networks:
      - radio.net
    depends_on:
      - radio.db


  radio.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: radio.env
    ports:
      - '3307:3306'
    networks:
      - radio.net
    volumes:
      - ../server/sql:/var/sql

  adminer:
    image: adminer
    env_file: radio.env
    ports:
      - '8082:8080'
    networks:
      - radio.net